version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: tritium-core
    container_name: tritium-core
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - tritium

  db:
    image: mariadb:10
    container_name: tritium-core-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: origin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mariadb
    volumes:
      - ./.data/db:/docker-entrypoint-initdb.d
    networks:
      - tritium
    ports: 
      - '3306:3306'

  nginx:
    image: nginx:alpine
    container_name: tritium-core-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - tritium

networks:
  tritium:
    driver: bridge